name: Docker Image No Cache

on: [workflow_dispatch, push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:    
    - uses: actions/checkout@v1
      with:
        fetch-depth: 0

    - name: Initialize Script
      run: |
        echo "Hallo world"
